version: "3"

services:
    client:
        image: nginx:1.17-alpine
        ports:
            - 3000:80
            - 3443:443
        volumes:
            - ./dist:/var/www
            - ./conf:/etc/nginx/conf.d
            - ./certs:/etc/ssl/certs

